### ISSUE TITLE
Deleting unnecessary database records of EVERYBODY's databases in Mongo

### ISSUE THREAD

**Issue by ekingungor** [bounswe/2021SpringGroup10#108]
We had executed lots of Postman entries to make testings, see how it's working and so on. The database has lots of meaningless entries in everybody's database. Only @OnurSefa has the access to database. These meaningless records should be deleted from the database.

 If anyone has special requests about database records, please comment under this issue. 
@ENESAYDOGDUOGLU @gulsahc  @ekremgezgen @safaaltunel @tahakalkanli @gkberk @fleafclover

**Comment by ENESAYDOGDUOGLU** [comment]
Onur can you delete unnecessary records of catfacts collection?

**Comment by tahakalkanli** [comment]
There are few documents that I am using for testing so deleting the records in "messages" index might not be a good idea.

**Comment by safaaltunel** [comment]
Yes you can clear my database collection. It is named "safa". Unfortunately it is not a descriptive name for my api but onur sefa named my collection. Blame him :)
p.s. onur please do not troll my collection because I said this. @OnurSefa

**Comment by gulsahc** [comment]
You can leave one entry in my database collection and delete the rest.

**Comment by OnurSefa** [comment]
> @OnurSefa can you delete unnecessary records of catfacts collection?

I have done deleting unnecessary facts. There are still some documents. You may inspect them via get all facts functionality of your example app. Let me know if you have an another issue.

**Comment by OnurSefa** [comment]
> There are few documents that I am using for testing so deleting the records in "messages" index might not be a good idea.

@tahakalkanli 
I did not perform any changes in your collection named "messages".

**Comment by OnurSefa** [comment]
> Yes you can clear my database collection. It is named "safa". Unfortunately it is not a descriptive name for my api but onur sefa named my collection. Blame him :)
> p.s. onur please do not troll my collection because I said this. @OnurSefa

@safaaltunel 
You may requested another name, I am always here for you :smiling_imp:
Anyway I have cleared your collection entirely.

**Comment by OnurSefa** [comment]
> You can leave one entry in my database collection and delete the rest.

@gulsahc 
I removed every document in weather collection other than a document which gives information about Istanbul's weather. You may test it with your application.

**Comment by gkberk** [comment]
My API key and app's search history are stored in db, deleting search history wouldn't be a problem, however 'thekey' index is very essential to me :)

**Comment by OnurSefa** [comment]
> My API key and app's search history are stored in db, deleting search history wouldn't be a problem, however 'thekey' index is very essential to me :)

@gkberk
Then, I do not attempt any changes in your collection.
