### ISSUE TITLE
Creating Google Docs page for Group Report

### ISSUE THREAD

**Issue by safaaltunel** [bounswe/2021SpringGroup10#113]
Hi, please share your Google docs page links here so we can contribute and observe what you have done for our group report.

**Comment by safaaltunel** [comment]
[Here](https://docs.google.com/document/d/18EgA84TuMXsGMklQPnDuIsw-CiYQt8jTikb5pffUxTQ/edit?usp=sharing) is link for evaluation of tools and processes

**Comment by tahakalkanli** [comment]
[Here](https://docs.google.com/document/d/1MJNYDZCOml2ATq2D5s440-p9vuBSei9n40OnhHTgPqc/edit?usp=sharing) is the google doc link for the challenges we met as a group. Feel free to edit and make suggestions.

**Comment by ENESAYDOGDUOGLU** [comment]
[Here](https://docs.google.com/document/d/1Dya04VSU4SW4QlxtjqA0dgEiPvk_hV_7Ze5vRvbFNac/edit?usp=sharing) is doc link for the list the status deliverables. Each group member can edit the file if necessary.

**Comment by gulsahc** [comment]
[Here](https://drive.google.com/drive/folders/1btpNua1qwz515F2cuzsNyfo9daySZdYE?usp=sharing) is a drive link for the project plan. You can review the .pod file on projectlibre, or look at the .png files. If you want to make a suggestion or see something missing, please feel free to contact me.

**Comment by safaaltunel** [comment]
[Here](https://docs.google.com/document/d/1ktJjsPx6nFual_JoQ1DmMaoWroA3PrnnDrbsYqDPuJ8/edit?usp=sharing) is link for summary of work done by each team member. Do not forget to write what you have done
