### ISSUE TITLE
Preparing Project Plan

### ISSUE THREAD

**Issue by gkberk** [bounswe/2021SpringGroup10#114]
We(me and Gülşah) should take action for preparation of project plan as discussed in the group meeting. It needs to be submitted until 23.59 but we better finish it early and let our teammates see it and take their feedbacks. Avoice conference needs to be done on discord.

**Comment by gulsahc** [comment]
Let's meet at 18.00 on discord and prepare  new project plan by going through the project plan we prepared in M1

**Comment by gkberk** [comment]
It is done, I think we did a good job. [Here](https://drive.google.com/drive/folders/1btpNua1qwz515F2cuzsNyfo9daySZdYE) it can be seen. Now we will have some feedbacks from our team. However the feedbacks requires direct communication because there is limited time. The issue is over.
