### ISSUE TITLE
Creating Doodle to choose project

### ISSUE THREAD

**Issue by ekremgezgen** [bounswe/2021SpringGroup10#12]

**Comment by safaaltunel** [comment]
[Here](https://pollunit.com/polls/ssj-5j5ereq0splixxn7rw) is the poll link. The poll is based on preference ranking. This means that give 1 point to the most liked project(i.e. the rank is 1 among other projects), distribute other points to the other projects based on your preference ranking. At the end lowest averaged option will be selected as highest priority project.
