### ISSUE TITLE
Fix CORS Error we receive while handling requests from the frontend

### ISSUE THREAD

**Issue by ekingungor** [bounswe/2021SpringGroup10#145]
No request from the frontend is successfully responded by the API due to common CORS error. We should handle this to make frontend work.

I have created a [new branch](https://github.com/bounswe/2021SpringGroup10/tree/backend/CORS_error_fixing) to fix this issue with some code (still not fixing the issue). But I thought some of the code could still be used to solve the issue. So you can delete them if you find a solution otherwise keep what you want to keep.

We may even have to migrate to Django from Flask, if it turns out to be insolvable.

**Comment by OnurSefa** [comment]
Actually it is solvable with flask using [AWS gateways](https://aws.amazon.com/api-gateway/). We need to arange a coding session with one of the frontend team member to test our modifications immediately. @gkberk @ekremgezgen @tahakalkanli I have a plan and one of you is enough for the testing process.

**Comment by gkberk** [comment]
I can attend such a meeting, we shall do it ASAP! @OnurSefa

**Comment by OnurSefa** [comment]
The error has resolved and documentations about the newly generated endpoints can be found [here](https://github.com/bounswe/2021SpringGroup10/tree/develop/documents).
