### ISSUE TITLE
Create a dockerfile for backend flask application

### ISSUE THREAD

**Issue by OnurSefa** [bounswe/2021SpringGroup10#147]
We need to create a dockerfile which enables our project to run smoothly in the EC2 instance. We can use our experience from the Cmpe352 [practice application docker file](https://github.com/bounswe/2021SpringGroup10/blob/CmpE352/practice_app/Dockerfile)

**Comment by ekingungor** [comment]
docker file is created and has the path: `develop/purbee_backend/backend_source/dockerfile` where develop is our [develop branch](https://github.com/bounswe/2021SpringGroup10/tree/develop)
