### ISSUE TITLE
Summary of Contrubition

### ISSUE THREAD

**Issue by tahakalkanli** [bounswe/2021SpringGroup10#156]
Please fill the table in the [document](https://docs.google.com/document/d/1w5nSsFbbejM77cgOu5gXkCbU-SDwdbt2UdR1FzbdDnE/edit).

**Comment by OnurSefa** [comment]
I have done work associated me

**Comment by ENESAYDOGDUOGLU** [comment]
Thanks for the reminder, I added the summary about my works.

**Comment by gkberk** [comment]
I completed my part.

**Comment by gkberk** [comment]
It seems all of assignees are done with it, I'm closing the issue
