### ISSUE TITLE
Create proper docker image and run it on the EC2 machine

### ISSUE THREAD

**Issue by OnurSefa** [bounswe/2021SpringGroup10#188]
Our current repository includes community related endpoints. To serve these endpoints, new docker image should be created and served in the EC2 machine in the AWS.

**Comment by OnurSefa** [comment]
@ekingungor we got an "no module found named xxxxx" error again. I believe lastly you handled this problem and you can handle this bug.

**Comment by ekingungor** [comment]
Could you try changing 'import fields' to 'import .fields' in 'post_fields.py'

**Comment by OnurSefa** [comment]
from post import fields worked for me, thank you @ekingungor. I have named the new version as the cmpegroup10/purbee:v0.2 and pushed it also into the docker hub. I have deployed to our EC2 machine.
