### ISSUE TITLE
Login and signup pages needs enhancement

### ISSUE THREAD

**Issue by gkberk** [bounswe/2021SpringGroup10#205]
Navigation shall be implemented by using buttons instead of links. 
Cosmetic changes if you see necessary could be made.
There is a bug due to link put in the button which leads to sign in and signup attempts automatically into home page. This shall be resolved, if onChange function for button is implemented it would fix it.

**Comment by safaaltunel** [comment]
Required improvements are done in [this](https://github.com/bounswe/2021SpringGroup10/pull/216) pull request and waiting for approval
