### ISSUE TITLE
Cleaning database

### ISSUE THREAD

**Issue by berkaydemirtas** [bounswe/2021SpringGroup10#214]
Structures of some instances in post and post_types collections are not the same with expected structure. They had inserted into db during implementation of endpoints and should be deleted.

**Comment by OnurSefa** [comment]
In the [backend meeting](https://github.com/bounswe/2021SpringGroup10/wiki/Backend-Meeting-2021-12-20), we discussed this problem and saw a problem with related to all collections we have currently. Garbage data should be removed from all the collections. I took this responsibility.

**Comment by OnurSefa** [comment]
We are waiting end of the test operations to handle this issue.

**Comment by OnurSefa** [comment]
I have cleaned the database. Enjoy!
