### ISSUE TITLE
Frontend needs an endpoint for feed

### ISSUE THREAD

**Issue by gkberk** [bounswe/2021SpringGroup10#233]
Backend returns a list of post ids to frontend when feed is required. Then frontend sends a request per id. This is inefficient, if an endpoint that returns a desired amount of posts directly is implemented it would be better. Is it possible? If so, can you implement it?

**Comment by berkaydemirtas** [comment]
Two feed endpoints are implemented. One of them is community_feed and you can use it to get posts of a community. (Posts are ordered according to their creation times.) Other one is user_feed. This endpoint returns a list of posts that should be displayed in the home page of the given user. (List contains posts that is related with user's subscribed communites and other registered users that user follows.). This endpoints will be ready to use after deployment.
