### ISSUE TITLE
Profile_page endpoint is not working

### ISSUE THREAD

**Issue by safaaltunel** [bounswe/2021SpringGroup10#249]
Due to the changes on the backend, profile_page endpoint is not working. No matter what the request body is, it is always returning a message saying "user name is not valid". Please fix the issue as soon as possible.

**Comment by berkaydemirtas** [comment]
This issue is solved and extra 2 endpoints namely follow and unfollow for registered user are implemented . You can check the changes in the files from following PR : #271
