### ISSUE TITLE
Creating Glossary wiki page

### ISSUE THREAD

**Issue by OnurSefa** [bounswe/2021SpringGroup10#25]
Main goal is explaining Requirements page descriptions clear. If someone wonders about the terminology we used, he/she should be able to find a glossary page to clarify his/her thoughts without needing somebody from our team.
Glossary page is [here](https://github.com/bounswe/2021SpringGroup10/wiki/Glossary)

- [x] Onur Sefa
- [x] Taha

**Comment by OnurSefa** [comment]
I have added the glossary associated with the User Requirements page.

**Comment by tahakalkanli** [comment]
system-requirements glossary has also been added.
