### ISSUE TITLE
GET endpoints not working

### ISSUE THREAD

**Issue by gkberk** [bounswe/2021SpringGroup10#253]
POST endpoints are not working in AWS API gateway. I can't sync frontend with backend right now, can you guys fix it?
-I can't run the backend locally because docker doesn't work on my windows.
-I can't use ec2 instance either because of CORS policy error.

**Comment by OnurSefa** [comment]
I see the problem in here, AWS Api Gateway does not accept any json input data in GET requests. SO, we need to change the GET endpoints ASAP.

**Comment by OnurSefa** [comment]
I have changed the community page Get endpoint and created related pull request #263. After the merge operation AWS API Gateway also needed to be changed to see the effects on the frontend and mobile.

**Comment by OnurSefa** [comment]
With the some test on the production, we see that changing parameter mechanism from json to path solves our problem quickly.

**Comment by OnurSefa** [comment]
The obectives are implemented and can be seen in the pull reqeust #269

**Comment by OnurSefa** [comment]
After the tests, now they are reachable.
