### ISSUE TITLE
Frontend: Community page backend sync

### ISSUE THREAD

**Issue by gkberk** [bounswe/2021SpringGroup10#256]
Community page needs to be working according to example data given by backend team. Also, backend connection shall be established.

**Comment by safaaltunel** [comment]
Community page can talk with backend now. I asked from the backend team to return post type names for each community in [this](https://github.com/bounswe/2021SpringGroup10/issues/307) issue, they made necessary changes in [this](https://github.com/bounswe/2021SpringGroup10/pull/292) PR but changes broke the application so they reverted the changes in [this](https://github.com/bounswe/2021SpringGroup10/pull/298) PR. Other than that everything is working fine.
