### ISSUE TITLE
Adding Glossary to the Requirements Page

### ISSUE THREAD

**Issue by safaaltunel** [bounswe/2021SpringGroup10#28]
Please add your glossary under the Glossary heading in the Requirements page. Do not forget to add inline linking.

**Comment by OnurSefa** [comment]
Inline link to the glossary part was already there, but as you requested, [Glossary page](https://github.com/bounswe/2021SpringGroup10/wiki/Glossary) combined with the [Requirements page](https://github.com/bounswe/2021SpringGroup10/wiki/Requirements).
