### ISSUE TITLE
Preparing questions to be asked to customers.

### ISSUE THREAD

**Issue by ENESAYDOGDUOGLU** [bounswe/2021SpringGroup10#30]

**Comment by ENESAYDOGDUOGLU** [comment]
I created questions page and added the questions about user requirements.

**Comment by tahakalkanli** [comment]
@ekremgezgen took notes of system requirement related questions during our meeting. They have also been added to questions page.

**Comment by ENESAYDOGDUOGLU** [comment]
Questions about requirements were created and added to the questions page.
