### ISSUE TITLE
 Note the responses to the questions asked at the customer meeting

### ISSUE THREAD

**Issue by ENESAYDOGDUOGLU** [bounswe/2021SpringGroup10#32]
The answers given to the questions asked in the customer meeting with the TA should be noted and shared with the group members.

**Comment by safaaltunel** [comment]
We met with the TA in the meeting 6 and all the notes that I took are posted in the [meeting notes #6](https://github.com/bounswe/2021SpringGroup10/wiki/Meeting-Notes-%236)
