### ISSUE TITLE
creating mockups for scenario4

### ISSUE THREAD

**Issue by fleafclover** [bounswe/2021SpringGroup10#37]
Mockups about scenario4 (community post type creation)  should be created.

**Comment by gulsahc** [comment]
New scenario is created about community post types and described according to template. You can find it on the [User Scenarios and Mockups](https://github.com/bounswe/2021SpringGroup10/wiki/User-Scenarios-and-Mockups) page.

**Comment by anekinsky** [comment]
Necessary wireframes for the scenario 4 has been designed and shared with the team via whatsapp.
