### ISSUE TITLE
Arrange a meeting with Suzan Üsküdarlı and Egemen İşgüder

### ISSUE THREAD

**Issue by anekinsky** [bounswe/2021SpringGroup10#38]
A meeting for presentation of the scenario 4 should be arranged with Suzan Üsküdarlı and Egemen İşgüder.

All the work done for the Scenario 4 should be presented.
Relevant Issues: #35 #36 #37 

Also the feedbacks for the previous 3 scenarios should be listened.

**Comment by Egosis** [comment]
Adım geçiyor +1 puan :)
