### ISSUE TITLE
Implementation of Base Api Logic of Joke App

### ISSUE THREAD

**Issue by OnurSefa** [bounswe/2021SpringGroup10#56]
Users should see a joke and when they add a joke to their favorites we should be able to display when it wanted. Api documentation in [here](https://github.com/15Dkatz/official_joke_api).

**Comment by gkberk** [comment]
You can use https://public-apis.io/page/12 to find public APIs that you may need, there are plenty of APIs.

**Comment by OnurSefa** [comment]
Created the base of the Joke App and to work on this new feature I created a [branch](https://github.com/bounswe/2021SpringGroup10/tree/Joke_Flask_App). Mentioned resources was helpful.
