### ISSUE TITLE
Implementation of Market App which shows last information about stock prices

### ISSUE THREAD

**Issue by OnurSefa** [bounswe/2021SpringGroup10#58]
I know that [Berkay](https://github.com/bounswe/2021SpringGroup10/wiki/Berkay-Demirta%C5%9F) is interested in the economics era and he should develop an app to help individuals who want to see the information about stock prices of firms. Also there is a good [documentation](https://marketstack.com/documentation) which may help.

**Comment by fleafclover** [comment]
I have implemented it and writen its unit tests. We merged it to the practice_app. Everything is looking fine.
