### ISSUE TITLE
Adding Home Page for Practice App

### ISSUE THREAD

**Issue by OnurSefa** [bounswe/2021SpringGroup10#63]
Every team member has prepared a demo application to learn and practice about API logic with Flask. To stage every different app we need to have one main Home Page which performs a bridge utility.

**Comment by safaaltunel** [comment]
I pushed base.html folder in [SportEvent_App Branch](https://github.com/bounswe/2021SpringGroup10/tree/SportEvent_App). You can add your api path in the base.html file and push it again. Later merging I will check it out again and be sure that everyone's link is in there
