### ISSUE TITLE
Review for Joke App from Gokberk

### ISSUE THREAD

**Issue by OnurSefa** [bounswe/2021SpringGroup10#65]
I value your review. Review my Flask Example App and notify me about your enhancement ideas.

**Comment by gkberk** [comment]
Can you revise the PR? I think you pushed the wrong branch.

**Comment by OnurSefa** [comment]
Thanks, it was mistaken. You may visit the pull request, I have created new pull request with the correct branch.

**Comment by gkberk** [comment]
The review is given
