### ISSUE TITLE
Opening pull requests ASAP

### ISSUE THREAD

**Issue by safaaltunel** [bounswe/2021SpringGroup10#70]
Hi folks, please finish up your code and open a pull request so we can move on. I hope you have a nice day.

**Comment by ENESAYDOGDUOGLU** [comment]
I created an app and opened pull requests. You can view via this [link](https://github.com/bounswe/2021SpringGroup10/pull/73).

**Comment by ENESAYDOGDUOGLU** [comment]
Everybody opened pull requests, and all the codes merged into master.
