### ISSUE TITLE
Unit test implementation for Joke App

### ISSUE THREAD

**Issue by Gepsmin** [bounswe/2021SpringGroup10#72]
To test the capabilities of the app a unit test should be implemented. Also we should see whether the app is working as it is supposed to in every functionality. Remember some functionalities should return success if the user offered the correct inputs. But if the inputs are erroneous, functionalities should return errors. This situation should be tested too.

**Comment by OnurSefa** [comment]
I have created test.py which uses unit test mechanism which is offered by python. I have modified the helper functions regarding to. Related work can be visited from this [commit](https://github.com/bounswe/2021SpringGroup10/tree/test_joke_app).
