### ISSUE TITLE
Cat facts App having issues with post request

### ISSUE THREAD

**Issue by ENESAYDOGDUOGLU** [bounswe/2021SpringGroup10#79]
Hello mates! I wrote the code below but it does not work. I am using SQLAlchemy as database. Can you help about that mistakes?

app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///test.db'
db = SQLAlchemy(app)
CATFACTS_URL='https://cat-fact.herokuapp.com/facts'

@app.route('/catfacts', methods = ['GET', 'POST'])
def cat_facts():
    if request.method == "POST":
        _id = request.form["_id"]
        text = request.form["text"]
        endpoint = "http://127.0.0.1:5000"

        req = endpoint + "/api/v1.0/catfacts"
        headers = {'Content-type': 'application/json'}

        task = {"_id": _id, "text": text}

        response = requests.post(req, data=json.dumps(task), headers=headers)
        return redirect('/catfacts')

**Comment by safaaltunel** [comment]
Hi mate. We are currently using mongodb as our database. you can change your db and we can proceed fixing your bug.

**Comment by ENESAYDOGDUOGLU** [comment]
> Hi mate. We are currently using mongodb as our database. you can change your db and we can proceed fixing your bug.

OK Thanks I switched and open new collection .

client = pymongo.MongoClient("mongodb+srv://base_user:base_user_password@cluster0.dbcb9.mongodb.net/first")
db = client.first
cat_collection = db.catfacts

so what can I do to correct my code

**Comment by safaaltunel** [comment]
> > Hi mate. We are currently using mongodb as our database. you can change your db and we can proceed fixing your bug.
> 
> OK Thanks I switched and open new collection .
> 
> client = pymongo.MongoClient("mongodb+srv://base_user:[base_user_password@cluster0.dbcb9.mongodb.net](mailto:base_user_password@cluster0.dbcb9.mongodb.net)/first")
> db = client.first
> cat_collection = db.catfacts
> 
> so what can I do to correct my code

Hey, mate. Can I see your api so I can help.

**Comment by ENESAYDOGDUOGLU** [comment]
> > > Hi mate. We are currently using mongodb as our database. you can change your db and we can proceed fixing your bug.
> > 
> > 
> > OK Thanks I switched and open new collection .
> > client = pymongo.MongoClient("mongodb+srv://base_user:[base_user_password@cluster0.dbcb9.mongodb.net](mailto:base_user_password@cluster0.dbcb9.mongodb.net)/first")
> > db = client.first
> > cat_collection = db.catfacts
> > so what can I do to correct my code
> 
> Hey, mate. Can I see your api so I can help.


@app.route('/api/v1.0/catfacts', methods = ["GET", "POST"])
def cat_facts_api():
    if request.method == "POST":
        if not request.json or not 'text' in request.json:
            abort(400)
        text = request.json["text"]
        
        cat_facts = Catfacts(text = text)
        
        try:
            db.session.add(cat_facts)
            db.session.commit()
           
            return {'data': {'_id': cat_facts._id, 'text': cat_facts.text}}, 201
        except:
            return {'data': "there"}
    else:
        cat_facts = Catfacts.query.order_by(Catfacts._id).all()
        json_objects = []
        for fact in cat_facts:
            json_objects.append({'_id': fact._id, 'text': fact.text})
        return jsonify({'data': json_objects}), 200

**Comment by safaaltunel** [comment]
> > > > Hi mate. We are currently using mongodb as our database. you can change your db and we can proceed fixing your bug.
> > > 
> > > 
> > > OK Thanks I switched and open new collection .
> > > client = pymongo.MongoClient("mongodb+srv://base_user:[base_user_password@cluster0.dbcb9.mongodb.net](mailto:base_user_password@cluster0.dbcb9.mongodb.net)/first")
> > > db = client.first
> > > cat_collection = db.catfacts
> > > so what can I do to correct my code
> > 
> > 
> > Hey, mate. Can I see your api so I can help.
> 
> I get an error at that line
> ​result=response.json()
> 
> @app.route('/catfacts', methods = ['GET', 'POST'])
> def cat_facts():
> if request.method == "POST":
> _id = request.form["_id"]
> text = request.form["text"]
> endpoint = "http://127.0.0.1:5000"
> 
> ```
>     req = endpoint + "/api/v1.0/catfacts"
>     headers = {'Content-type': 'application/json'}
> 
>     task = {"_id": _id, "text": text}
> 
>     response = requests.post(req, data=json.dumps(task), headers=headers)
>     return redirect('/catfacts')
> else:
>     endpoint = "http://127.0.0.1:5000"
> 
>     req = endpoint + "/api/v1.0/catfacts"
>     headers = {'Content-type': 'application/json'}
>     response = requests.get(req)
>     result=response.json()
>     cat_facts = result['data']
> 
>     return render_template('catfacts.html', cat_facts = cat_facts)
> ```
> 
> @app.route('/api/v1.0/catfacts', methods = ["GET", "POST"])
> def cat_facts_api():
> if request.method == "POST":
> if not request.json or not 'text' in request.json:
> abort(400)
> text = request.json["text"]
> 
> ```
>     try:
>         cat_collection.insert_one({'fact': text})
>        
>         return {'data': {'_id': cat_facts._id, 'text': cat_facts.text}}, 201
>     except:
>         return {'data': "there"}
> else:
>    cat_col
>     json_objects = []
>     for fact in cat_facts:
>         json_objects.append({'_id': fact._id, 'text': fact.text})
>     return jsonify({'data': json_objects}), 200
> ```

Hey, mate. I think maybe you do not provide an id in your user interface. So that your api caanot find an id and complains about it. Can you fix it?

**Comment by ENESAYDOGDUOGLU** [comment]
> > > > > Hi mate. We are currently using mongodb as our database. you can change your db and we can proceed fixing your bug.
> > > > 
> > > > 
> > > > OK Thanks I switched and open new collection .
> > > > client = pymongo.MongoClient("mongodb+srv://base_user:[base_user_password@cluster0.dbcb9.mongodb.net](mailto:base_user_password@cluster0.dbcb9.mongodb.net)/first")
> > > > db = client.first
> > > > cat_collection = db.catfacts
> > > > so what can I do to correct my code
> > > 
> > > 
> > > Hey, mate. Can I see your api so I can help.
> > 
> > 
> > I get an error at that line
> > ​result=response.json()
> > @app.route('/catfacts', methods = ['GET', 'POST'])
> > def cat_facts():
> > if request.method == "POST":
> > _id = request.form["_id"]
> > text = request.form["text"]
> > endpoint = "http://127.0.0.1:5000"
> > ```
> >     req = endpoint + "/api/v1.0/catfacts"
> >     headers = {'Content-type': 'application/json'}
> > 
> >     task = {"_id": _id, "text": text}
> > 
> >     response = requests.post(req, data=json.dumps(task), headers=headers)
> >     return redirect('/catfacts')
> > else:
> >     endpoint = "http://127.0.0.1:5000"
> > 
> >     req = endpoint + "/api/v1.0/catfacts"
> >     headers = {'Content-type': 'application/json'}
> >     response = requests.get(req)
> >     result=response.json()
> >     cat_facts = result['data']
> > 
> >     return render_template('catfacts.html', cat_facts = cat_facts)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @app.route('/api/v1.0/catfacts', methods = ["GET", "POST"])
> > def cat_facts_api():
> > if request.method == "POST":
> > if not request.json or not 'text' in request.json:
> > abort(400)
> > text = request.json["text"]
> > ```
> >     try:
> >         cat_collection.insert_one({'fact': text})
> >        
> >         return {'data': {'_id': cat_facts._id, 'text': cat_facts.text}}, 201
> >     except:
> >         return {'data': "there"}
> > else:
> >    cat_col
> >     json_objects = []
> >     for fact in cat_facts:
> >         json_objects.append({'_id': fact._id, 'text': fact.text})
> >     return jsonify({'data': json_objects}), 200
> > ```
> 
> Hey, mate. I think maybe you do not provide an id in your user interface. So that your api caanot find an id and complains about it. Can you fix it?

Oh you are right , I will change my code. Thanks for help

**Comment by ENESAYDOGDUOGLU** [comment]
I still have a problem 


else:

        cat_facts = cat_collection.find({})
        
        json_objects = []
        for fact in cat_facts:
            json_objects.append({'fact': fact.fact})
        print(json_objects)
        return {'data': json_objects}

**Comment by safaaltunel** [comment]
> Here is my get request from Api. I have fact field in my collection .I still have a problem
> 
> else:
> 
> ```
>     cat_facts = cat_collection.find({})
>     
>     json_objects = []
>     for fact in cat_facts:
>         json_objects.append({'fact': fact.fact})
>     print(json_objects)
>     return {'data': json_objects}
> ```

Hey, mate. I think you are trying to reach your fact field in your collection. But you are doing it wrong. you should reach it by something like this:
'''
json_objects.append({'fact': fact["fact"]})
'''
I think this will solve your problem. If you have any, do not hesitate to ask! Good Work!!

**Comment by ENESAYDOGDUOGLU** [comment]
> > Here is my get request from Api. I have fact field in my collection .I still have a problem
> > else:
> > ```
> >     cat_facts = cat_collection.find({})
> >     
> >     json_objects = []
> >     for fact in cat_facts:
> >         json_objects.append({'fact': fact.fact})
> >     print(json_objects)
> >     return {'data': json_objects}
> > ```
> 
> Hey, mate. I think you are trying to reach your fact field in your collection. But you are doing it wrong. you should reach it by something like this:
> '''
> json_objects.append({'fact': fact["fact"]})
> '''
> I think this will solve your problem. If you have any, do not hesitate to ask! Good Work!!

Thanks a lot mate
