### ISSUE TITLE
Review for Weather Api from Ekin

### ISSUE THREAD

**Issue by gulsahc** [bounswe/2021SpringGroup10#80]
Weather api is provided in Weather_App branch. Please review the code and give feedbacks.

**Comment by ekingungor** [comment]
God bless your hands.

I have noticed a couple of things.

 - [Here](https://github.com/bounswe/2021SpringGroup10/blob/8ade3efef40caaafbf0fd7b52a56a412d9ef5b9c/practice_app/app.py#L28) the method says, it's a POST, but in the header methods parameter =['GET']. Maybe there was a confusion.

- [Here](https://github.com/bounswe/2021SpringGroup10/blob/8ade3efef40caaafbf0fd7b52a56a412d9ef5b9c/practice_app/app.py#L30) Looks like you are checking a string response. Couldn't be sure if you can directly check that without using keys. Maybe you can write a test case for that.

Other than these minor issues, it looks good. Well done.

**Comment by gulsahc** [comment]
- Method name refers to weatherpost function since the functionality of weatherpostindex is to render the template of the response.
- Check for string is for error handling, the response of the weather api will be checked by a test case as you mentioned.

**Comment by ekingungor** [comment]
Now I see. Great! Also I have checked and approved your [pull request](https://github.com/bounswe/2021SpringGroup10/pull/69). Great job.
