### ISSUE TITLE
Watched Movie App having issues with post movies

### ISSUE THREAD

**Issue by ekremgezgen** [bounswe/2021SpringGroup10#82]
Hello mates. When i try to add movie to mongo i have take error. This is the photos of error.
![Capture](https://user-images.githubusercontent.com/47948423/121219207-1f3cff80-c88c-11eb-8007-181db994ae59.PNG)
Can anyone help me? Thanks.

**Comment by safaaltunel** [comment]
Hey, mate. Can I see your html page. I think your request.form dictionary does not have a "addshow" field.

**Comment by ekremgezgen** [comment]
> Hey, mate. Can I see your html page. I think your request.form dictionary does not have a "addshow" field.

![Capture1](https://user-images.githubusercontent.com/47948423/121219520-74791100-c88c-11eb-9a4c-cfd9f47f4f13.PNG)

**Comment by safaaltunel** [comment]
Hey, mate. I think you resolved your issue. I'm closing it now. If you encounter another problem, please do not hesitate to reopen again.
