### ISSUE TITLE
Create a collection in Mongo, for my News API's data base 

### ISSUE THREAD

**Issue by ekingungor** [bounswe/2021SpringGroup10#83]
Everybody in the group has transferred their databases to Mongo DB, so to not violating the common practice, I am planning to transfer my database from SQLAlchemy to Mongo DB either.
@OnurSefa , could you please create a collection for me.

**Comment by ENESAYDOGDUOGLU** [comment]
I asked Onur Sefa to create a collection for me and he created a collection called "catfacts". I use it in my App.

**Comment by OnurSefa** [comment]
@ekingungor If you want to choose a name, send me it. Otherwise I can create a collection with name "ekin".

**Comment by ekingungor** [comment]
News, would be nice. Thanks in advance.

**Comment by OnurSefa** [comment]
Done. you may reach your collection as follows
`
client = pymongo.MongoClient("mongodb+srv://base_user:base_user_password@cluster0.dbcb9.mongodb.net/first")
db = client.first
<your_collection_name> = db.news`
