### ISSUE TITLE
Testing mechanism for Joke App need Review from Gulsah

### ISSUE THREAD

**Issue by OnurSefa** [bounswe/2021SpringGroup10#85]
I have created a new branch to implement the unit tests. When I run the test separately and together. I did not encounter with any problem. I want you to inspect my implementation. Remember, I also added a new API which delete a user from mongoDB. Also the return types of helper functions are modified.

**Comment by gulsahc** [comment]
I posted [my review](https://github.com/bounswe/2021SpringGroup10/pull/84#issuecomment-856941528) on the pull request. Well done!
