### ISSUE TITLE
Testing mechanism for Joke App need Review from Berkay

### ISSUE THREAD

**Issue by OnurSefa** [bounswe/2021SpringGroup10#86]
I have created a new branch to implement the unit tests. When I run the test separately and together. I did not encounter with any problem. I want you to inspect my implementation. Remember, I also added a new API which delete a user from mongoDB. Also the return types of helper functions are modified.

**Comment by fleafclover** [comment]
I have reviewed the unit test functions and write my review to the pull request. You can merge it now.
