### ISSUE TITLE
Reviewing folder structure

### ISSUE THREAD

**Issue by safaaltunel** [bounswe/2021SpringGroup10#88]
Hello everyone,
Please review your folder structure and add your code in the folder named "practice_app" so that we will not have a mergeing conflict. Thanks!

**Comment by OnurSefa** [comment]
I have merged the first version of my application to the master. Also added minor upgrades for the good of the team. I have also created a new branch which includes the unit test. I am waiting for reviews so that I can merge again with the master

**Comment by gulsahc** [comment]
I updated folder structure of Weather_App based on master. Also added directory 'tests' to include unittests.

**Comment by safaaltunel** [comment]
> I have merged the first version of my application to the master. Also added minor upgrades for the good of the team. I have also created a new branch which includes the unit test. I am waiting for reviews so that I can merge again with the master

Thanks mate, I've updated my folder structure based on yours.

**Comment by ekingungor** [comment]
I have updated my folder structure according to the master branch. Now ready to merge.

**Comment by OnurSefa** [comment]
I have also merged the final version of the joke app.

**Comment by tahakalkanli** [comment]
Merging is mostly done according to mentioned folder structure. Thank you everybody <3
