### ISSUE TITLE
I need some help to migrate my database from SQLAlchemy to MongoDB

### ISSUE THREAD

**Issue by ekingungor** [bounswe/2021SpringGroup10#95]
My api was working properly before migrating the database from SQLAlchemy to MongoDb. Now I have a couple of test cases that are problematic. I would appreciate your help with MongoDb.

**Comment by OnurSefa** [comment]
We did [discord](https://github.com/bounswe/2021SpringGroup10/wiki/Communication-Plan) meeting with Ekin and I helped him to get the base logic of the mongoDB implementation on python.

We used the following resources: [insert_one](https://www.geeksforgeeks.org/python-mongodb-insert_one-query/), [find](https://www.w3schools.com/python/python_mongodb_find.asp), and [mongoDB](https://docs.mongodb.com/).

There were some bugs in the code. First of all mongoDB assigns '_id' to the document when it is not defined. Also assigns a unique id object to this key and it is not json serializable. Detailed explanation can be found in the [ObjectId](https://docs.mongodb.com/manual/reference/method/ObjectId/) page. I showed how to avoid getting this '_id' value.

End of the day titles should be unique, so we implemented the following code:
```python
    elif request.method == "POST":
        req = request.values.to_dict()
        if not req:
            req = request.json

        my_new_news = {"_id":req["title"],
        "source":req["source"],
        "title":req["title"],
        "description":req["description"],
        "date":req["date"],
        "url":req["url"]}

        try:
            news_collection.insert_one(my_new_news)
```
This code  segment can be observed in app.py file.
This way returned object from the database is now serializable and using get operations more easier. Also we encountered a  passing argument problem when testing the api. The parameter passing mechanisms to an api can be found in [here](https://customercare.igloosoftware.com/support/developers/kb/articles/different_ways_to_pass_data_in_your_api_calls) in a compact manner.
Ekin wanted to use two different mechanism for his Post api which are passing with a json and with form data. 
Recommended reading is [here](https://www.digitalocean.com/community/tutorials/processing-incoming-request-data-in-flask). This explanation offers how to use different methods in a flask application. 
```python
        req = request.values.to_dict()
        if not req:
            req = request.json
```
mechanism allows the application to look for the to different methods. If the form data is empty it gets the data from json and if it is full, application already good to go.
