### ISSUE TITLE
Bug: catfacts_test.py Assertion Mistake

### ISSUE THREAD

**Issue by OnurSefa** [bounswe/2021SpringGroup10#98]
I have tested the our application and found out that 4th test fails in catfacts_test.py line 41.
```python
    def test_api_add_catfact(self):
        tester = app.test_client(self)
        req = "/api/v1.0/catfacts"
        headers = {'Content-type': 'application/json'}
        fact = "Cats like people"
        catfact = {"fact": fact}
        response = tester.post(req, data=json.dumps(catfact), headers=headers)
        status = response.status_code
        self.assertEqual(201, status)
```

The error message says that status returned 200 code but our post schema need 201 code. 
```python
            cat_collection.insert_one({'fact': fact})
          
            return {'fact':fact}
```
I think that error is addressed here and I gave the regarding code segment which is in app.py line 202.
I believe that you @ENESAYDOGDUOGLU may want to change it as follows:
```python
            cat_collection.insert_one({'fact': fact})
          
            return {'fact':fact}, 201
```
With the given addition, when the operation is succeeded, you will be able to return 201 status code which implements some addition has occurred. And still if you want to return 200 status code to the user you may use the following code segment which implements catfacts_test.py:
```python
    def test_api_add_catfact(self):
        tester = app.test_client(self)
        req = "/api/v1.0/catfacts"
        headers = {'Content-type': 'application/json'}
        fact = "Cats like people"
        catfact = {"fact": fact}
        response = tester.post(req, data=json.dumps(catfact), headers=headers)
        status = response.status_code
        self.assertEqual(200, status)
```
Regarding some information about status code may be found [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status).

**Comment by ENESAYDOGDUOGLU** [comment]
Thanks a lot mate I update [app.py](https://github.com/bounswe/2021SpringGroup10/blob/master/practice_app/app.py) line 205.
