### ISSUE TITLE
Bug: movie_test.py Assertion Mistake

### ISSUE THREAD

**Issue by OnurSefa** [bounswe/2021SpringGroup10#99]
I have tested your @ekremgezgen unit test which implemented in movie_test.py and encounter with a fail in the following unit test:
```python
    def test_api_add_movie(self):
        tester = app.test_client(self)
        req = "/api/v1.0/movie"
        headers = {'Content-type': 'application/json'}
        mmovie = "Eyes Wide Shut"
        movies = {"mmovie": mmovie}
        response = tester.post(req, data=json.dumps(movies), headers=headers)
        status = response.status_code
        self.assertEqual(201, status)
```
I assume you want to get 201 status code from post request but don't send it to the api user. 
```python
    def test_api_add_movie(self):
        tester = app.test_client(self)
        req = "/api/v1.0/movie"
        headers = {'Content-type': 'application/json'}
        mmovie = "Eyes Wide Shut"
        movies = {"mmovie": mmovie}
        response = tester.post(req, data=json.dumps(movies), headers=headers)
        status = response.status_code
        self.assertEqual(200, status)
```
This change would resolve your failure in the unit test but I assume that you want to go with the 201 status code because of the traditional instincts and to be consistent with the public opinion.
```python
        try:
            movie_collection.insert_one({'mmovie': mmovie})
          
            return {'mmovie':mmovie}
```
I see that you do not return any status code in the app.py line 276 and python creates automatic response answer with status code 200 when everything is as supposed to. 
```python
        try:
            movie_collection.insert_one({'mmovie': mmovie})
          
            return {'mmovie':mmovie}, 201
```
would resolve your issue. Also there is a some bug mentioned #98 in here.

**Comment by ekremgezgen** [comment]
Necessary updates are done in the master branch. Thanks for your testing and information.
